spring.application.name=ApiGuard

spring.datasource.url=jdbc:postgresql://ep-red-bird-an4obwlm-pooler.c-6.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8eClxZFB1niW

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true